### ISSUE TITLE
Bug: Crashing with BCLib

### ISSUE THREAD

**Issue by SHXRKIEgg** [devs-immortal/The-Aether#664]
### What happened?

Unable to play with Better Nether and/or Eden Ring Mods as its Dependency mod, BCLib, Crashes with Paradise Lost.

Add Better Nether or Eden Ring Mods with its dependency BCLib and Crash on Startup

### Mod Version

paradise-lost-1.6.8+1.18.2.jar

### Fabric API Version

fabric-api-0.50.0+1.18.2.jar

### Relevant log output

```Shell
[11:25:40] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[11:25:40] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[11:25:45] [ForkJoinPool-1-worker-10/WARN]: The mod "thonkutil-customization-v1" contains invalid entries in its mod json:
- Unsupported root entry "disabled:mixins" at line 11 column 20
[11:25:45] [main/INFO]: Dependencies overridden for crusade, kubejs, disenchanter, ezpas, incantationem, quarryplus, trinkets, fuelinfo, bettersleeping, morevillagers-fabric, lambdabettergrass, mcdar, fabric-dimensions-v1, kibe, rad, betternether, apoli, megane, torohealth, adventurez, agape_space, villager-hats, resourceful_tools, jump, bewitchment, iris, sandwichmod, kambrik, veggie_way, clickadv, pickupnotifier, playerabilitylib, dynview, mo_glass, terrarianslimes, chat_heads, ninjaphenix_container_lib, fabric-diagonal-panes, minieffects, silkspawners, balm-fabric, kjsextras, dawn, advancementplaques, tinyskeletons, cleancut, bcc, bitsandchisels, repurposed_structures, modmenu, magiccombatwands, no-telemetry, ironfurnaces, quartzelv, hookshot, botania, origins, disable_custom_worlds_advice, morerespawnanchors, mocolors, megane-runtime, dripstone_fluid_lib, libblockattributes_fluids, marketcrates, adorn, morebannerfeatures, cloth-config, conjuring, krypton, customwindowtitle, aqupdgrizzly, someforgepatchesported, detailab, geckolib3, veinmining, multipart_entities, cleardespawn, waterdripsound, clienttweaks, notes, mambience, dusk, wi_zoom, enhanced_attack_indicator, placeholder-api, onsoulfire, ae2, maelstrom_library, graveyard, lithium, goblintraders, harvest_scythes, things, simple_shelves, libblockattributes, mcdw, fallingleaves, milk_plus, awesomedungeon, additionalbars, mcda, seasons, farmingforblockheads, go-fish, reach-entity-attributes, starlight, simplemeasuring, deathlog, carpet, chalk, cosmetic-armor, libblockattributes_core, drippyloadingscreen, polymer, horsestatsvanilla, ruined_equipment, jankson, bakingmod, animal_feeding_trough, origins-classes, fabric-renderer-indigo, goosik-config, teenycoal, invview, bsvsb, forgeconfigapiport, calio, paintings, libgui, xaerominimap, croptopia, fabric-rendering-v0, stonecutter_recipe_tags, fabricenchantments, omega-config, givemehats, mtmechs, continuity, inmis, torchbowmod, lifts, can-i-mine-this-block, visuality, puzzleslib, extragenerators, dragonloot, horseinfo, team_reborn_energy, mythicmetals, notenoughcrashes, autorun, no_null_processors, preciseblockplacing, universal-graves, enchantment_lore, satin, pugh_lib, architects_palette, guardiansgalore, server_translations_api, mcf-reap, glassential, rpgstats, villagernames, eldritch_mobs, xaeroworldmap, lambdynlights, wmitaf, compress, mining_dims, twigs, buildinggadgets, consistency_plus, cardinal-components-level, lumiwool, miningutility, fabric-blockrenderlayer-v1, simple_backpack, libblockattributes_items, aqupdcaracal, carpet-extra, fabric, respawnablepets, bclib, dummmmmmy, pride, cosmetica, slimyfloor, konkrete, experiencebugfix, equipmentcompare, fireworkfrenzy, catwalksinc, pugh_tools, farmersdelight, justenoughkeys, packet_tweaker, fireplacelib, mythic-mounts, skinlayers, greater_eye, tolaserblade, elementalcreepers, extraorigins, culinaire, enchant_giver, blockus, capybara, fabric-events-interaction-v0, whereisit, bountiful, patchouli, thonkutil, betterthirdperson, gobber2, malilib, expandedstorage, redstonebits, cardinal-components-entity, inventoryprofilesnext, architectury, authme, cardinal-components-base, campchair, earthtojavamobs, fabric-item-groups-v0, mavm, chas, fabric-renderer-api-v1, seedfix, craftpresence, creativeonepunch, rhino, salem, cardinal-components-block, ae2wtlib, doom, owo, trashslot, wfw, soaringstructures2, impersonate, alloy_forgery, hammermod, zihlaunchpads, waystones, clumps, exlineawnings, companion_bats, itemborders, cardinal-components-item, entitybanners, unforgivingvoid, lazydfu, modern_industrialization, chesttracker, lovely_snails, bosses_of_mass_destruction, terralith, coat, fabric-renderer-registries-v1, beehivetooltips, cspirit, annotateddi, arcanus, friendsandfoes, craftingtweaks, lank, enchdesc, additionaladditions, static-content, ward_blocks, fluidtank, roughlyenoughitems, voidz, hologram-api, iceberg, legendarytooltips, sgui, spruceui, carpet-tis-addition, cardinal-components-world, fancymenu, indium, fabric-biome-api-v1, ferritecore, chisel, itemscroller, heartbond, betterf3, carrier, dark-enchanting, exlinefurniture
[11:25:45] [main/INFO]: Loading 327 mods:
	- additionaladditions 3.0.1
	- additionalbars 3.0.0
	- additionalstructures 3.0.3
	- adorn 3.4.0+1.18.2
	- advanced_runtime_resource_pack 0.5.5 via carrier
	- advancements-enlarger 0.2.4
	- advdebug 2.3.0
	- adventurez 1.4.10
	- aqupdcaracal 1.18.2-1.3.8
	- aqupdgrizzly 1.18-1.3
	- architects_palette 1.7
	- architectury 4.2.48
	- attributefix 14.0.1
	- autoconfig1u 3.4.0
	- axolotlitemfix 1.1.3
	- balm-fabric 3.0.0+0
	- basicshields 1.3.1-1.18.2
	- bcc fabric-1.0.5
	- bclib 1.4.3
	- betterf3 1.2.4
	- betternether 6.1.0
	- betterthirdperson 1.7.3
	- bhmenu 1.17.1-1.18.2-1.3
	- biomeinfo 1.18.2-10
	- biomemakeover 1.18.2-1.4.17
	- blockus 2.4.3+1.18.2
	- blue_endless_jankson 1.2.1 via jankson
	- blur 2.4.1
	- bookshelf 13.0.12
	- bosses_of_mass_destruction 1.3.6-1.18.2
	- byg 1.4-RC-8
	- capybara 1.0.3
	- cardinal-components 4.1.4
	- cardinal-components-base 4.1.4 via cardinal-components
	- cardinal-components-block 4.1.4 via cardinal-components
	- cardinal-components-chunk 4.1.4 via cardinal-components
	- cardinal-components-entity 4.1.4 via cardinal-components
	- cardinal-components-item 4.1.4 via cardinal-components
	- cardinal-components-level 4.1.4 via cardinal-components
	- cardinal-components-scoreboard 4.1.4 via cardinal-components
	- cardinal-components-world 4.1.4 via cardinal-components
	- carrier 1.10.0
	- charm 4.0.0
	- charmonium 4.0.0
	- cherishedworlds 2.0.1-1.18
	- chipped 1.2
	- clienttweaks 7.1.0
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.2.57
	- clumps 8.0.0+7
	- coat 1.0.0-beta.17+mc1.18.2 via wandering_collector
	- collective-fabric 4.26
	- com_electronwill_night-config_core 3.6.4 via terrablender
	- com_electronwill_night-config_toml 3.6.4 via terrablender
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- com_github_luben_zstd-jni 1.5.2-2 via dashloader
	- com_moandjiezana_toml_toml4j 0.7.2 via charm
	- com_typesafe_config 1.4.1 via croptopia
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
	- comforts 1.1.2-1.18.2
	- continuity 1.1.0+1.18.2
	- controlling 9.0+17
	- crafttweaker 9.1.98
	- crawl 0.10.4
	- creatures_of_the_jungle 1.0.0
	- creeperoverhaul 1.3.0
	- croptopia 1.8.3
	- crowdin-translate 1.4+1.18.2 via basicshields
	- cullleaves 2.3.2
	- customportalapi 0.0.1-beta50-1.18 via the_aether
	- darkpaintings 10.0.1
	- dashloader 3.1.1+1.18
	- dawn 3.3.0
	- decorative_blocks 2.1.0
	- deepslatecutting 1.3.2
	- deleteworldstotrash 3.2.0
	- dev_quantumfusion_dashloader_dashloader-core 1.4.0 via dashloader
	- dev_quantumfusion_hyphen 0.2.0 via dashloader
	- dragonloot 1.0.10
	- drippyloadingscreen 1.5.1
	- duckling 1.0.3
	- dustrial_decor 0.5
	- dynamicfps 2.1.0
	- earthtojavamobs 1.8.0+1.18.2
	- easymagic 3.3.0
	- easyshulkerboxes 3.1.1
	- eatinganimationid 1.6
	- ecologics 1.5.2
	- elytratrinket 3.0.0-1.18.1
	- enchantment_lore 1.2.6-1
	- enchdesc 10.0.2
	- endgoblintraders 1.5 (Re-upload)
	- enhanced_attack_indicator 1.0.3+1.18
	- entityculling 1.5.1
	- equipmentcompare 1.2.12
	- extended_armor_bars 1.2.1
	- fabric 0.50.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.6.0+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.4+7b0f312660 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.3+d82b939260 via fabric
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.14+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.4.0+4457765560 via fabric
	- fabric-item-groups-v0 0.3.11+91896a4960 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-language-kotlin 1.7.3+kotlin.1.6.20
	- fabric-lifecycle-events-v1 2.0.3+2d83e92c60 via fabric
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.1.0+81ea5b3c60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.0+fe4ddef060 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via spark
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.4.17+d8c7b9ae60 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-resource-loader-v0 0.4.18+2de5574560 via betterf3
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.2.0+1f6558e860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.6.0+2373a54560 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+40c91ec860 via fabric
	- fabricloader 0.13.3
	- fabricshieldlib 1.5.3-1.18
	- fake-player-api 0.3.0 via the_bumblezone
	- fallingleaves 1.10.0+1.18.2
	- fallingtree 3.5.0b1
	- fancymenu 2.6.4
	- faux-custom-entity-data 2.0.1
	- feature_nbt_deadlock_be_gone 2.0.0+1.18.2-rc1
	- ferritecore 4.2.0
	- fiber 0.23.0-2 via collective-fabric
	- fiblib 1.3.1+1.18.2 via postmateria
	- forgeconfigapiport 3.2.0
	- forgottenrecipes 1.18.1-1.0.0
	- friendsandfoes 1.3.4
	- ftbchunks 1802.3.5-build.130
	- ftblibrary 1802.3.6-build.115
	- ftbquests 1802.3.8-build.101
	- ftbteams 1802.2.6-build.51
	- gateofbabylon 1.7.0-1.18.2
	- geckolib3 3.0.38
	- geodes 1.3.1
	- go-fish 1.5.0-1.18.2
	- goblintraders 1.5.1
	- goosik-config 0.2.0 via visuality
	- graveyard 1.7
	- guardvillagers 1.18.2-1.0.11
	- gud_recipe_confidence 1.0.2 via the_aether
	- highlighter 1.1.2
	- iceberg 1.0.38
	- illagerexp 0.1.5
	- immersive_weathering 2.4.0
	- impaled 1.1.1
	- incubus_core 1.6.6+1.18.2 via the_aether
	- indium 1.0.2+mc1.18.2
	- infusion_table 1.0.5
	- ingredient-extension-api 2.0.5
	- inmis 2.5.3-1.18.2
	- inventoryhud 3.4.2
	- io_leangen_geantyref_geantyref 1.3.11 via croptopia
	- iris 1.2.2-build.32
	- itemfilters 1802.2.7-build.21
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- kleeslabs 11.0.0
	- konkrete 1.3.3
	- krypton 0.1.9
	- lambdynlights 2.1.0+1.17
	- lazydfu 0.1.2
	- libgui 5.1.0+1.18 via additionaladditions
	- libninepatch 1.1.0 via libgui
	- lithium 0.7.9
	- lovely_snails 1.0.4+1.18
	- maelstrom_library 1.2.4-1.18.2 via bosses_of_mass_destruction
	- magnumtorch 3.1.2
	- mavm 1.0.7a
	- maybe-more-data 1.0.0-1.18.2 via deepslatecutting
	- me_hypherionmc_simple-rpc-common 1.0.20 via simple-rpc
	- megane 7.4.0
	- megane-api 7.1.0 via megane
	- megane-fabric-transfer 7.1.0 via megane
	- megane-runtime 7.2.0 via megane
	- megane-vanilla 7.1.0 via megane
	- midnightlib 0.4.0
	- minecraft 1.18.2
	- mm 2.3 via crawl
	- modid 1.0.0
	- modmenu 3.1.1
	- more-axolotls 1.0.2
	- more_babies 0.5.1
	- moreachievements 1.0.8
	- moretags 3.0.3 via the_aether
	- morevillagers-fabric 3.2.0-SNAPSHOT
	- mostructures 1.4.1+1.18.2
	- mousetweaks 2.22
	- multipart_entities 1.1.5-1.18.2 via bosses_of_mass_destruction
	- naturescompass 1.18.2-2.0.3-fabric
	- nears 1.1.6
	- notenoughanimations 1.6.0
	- omega-config 1.2.3-1.18.1 via inmis
	- onsoulfire 1.18-1
	- org_anarres_jcpp 1.4.14 via iris
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_javassist_javassist 3.28.0-GA via crafttweaker
	- org_jetbrains_kotlin_kotlin-reflect 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.2 via fabric-language-kotlin
	- org_joml_joml 1.10.2 via sodium
	- org_reflections_reflections 0.10.2 via crafttweaker
	- org_spongepowered_configurate-core 4.1.2 via croptopia
	- org_spongepowered_configurate-hocon 4.1.2 via croptopia
	- overweight_farming 1.18.2-1.2.0-fabric
	- oxidized 1.6.3
	- paintings 9.1.1.0
	- patchouli 1.18.2-67-FABRIC
	- paxi 1.18.2-Fabric-2.0
	- phosphor 0.8.1
	- pickupnotifier 3.2.0
	- pigsteel 1.7.1
	- placeholder-api 1.1.3+1.17.1 via styledchat
	- player-data-api 0.1.0+1.18 via styled-nicknames
	- plushies 1.2
	- polymorph 0.0.20-1.18.2
	- postmateria 1.0.0-1.18.2
	- pride 1.1.0+1.17 via lambdynlights
	- puzzle 1.2.1
	- puzzle-base 1.2.1 via puzzle
	- puzzle-gui 1.2.1 via puzzle
	- puzzle-models 1.2.1 via puzzle
	- puzzle-splashscreen 1.2.1 via puzzle
	- puzzleslib 3.3.1
	- quartzelv 2.1.1+1.18
	- reach-entity-attributes 2.1.1 via gateofbabylon
	- repurposed_structures 4.1.3+1.18.2
	- rightclickharvest 1.5.1
	- roughlyenoughitems 8.1.449
	- roughlyenoughprofessions 1.0.1
	- roughlyenoughresources 2.5.0
	- runelic 11.0.1
	- satin 1.7.2 via the_aether
	- sentimentality3 1.4.12
	- simple-rpc 2.7.3
	- sit 1.18.2-18
	- skinlayers 1.4.3-mc1.18.2
	- skylorlib 1.2.3
	- sodium 0.4.1+build.15
	- spark 1.8.14
	- spirit 1.2.3
	- sprout 1.0.0
	- spruceui 3.3.0+1.17 via lambdynlights
	- starterkit-fabric 3.1
	- stoneholm 1.4.3
	- styled-nicknames 1.0.4+1.18
	- styledchat 1.2.3+1.18
	- terrablender 1.1.0.99
	- terraform-wood-api-v1 3.0.0 via blockus
	- the_aether 1.6.8+1.18.2
	- the_bumblezone 5.0.10+1.18.2
	- thonkutil 2.12.0+1.18
	- thonkutil-base 1.12.0+93f5607360 via thonkutil
	- thonkutil-capes-v1 1.3.1+974d16dd60 via thonkutil
	- thonkutil-coords-v1 1.0.18+4c66479160 via thonkutil
	- thonkutil-customization-v1 1.0.13+4c66479160 via thonkutil
	- thonkutil-legacy 1.0.19+aa74e18060 via thonkutil
	- thonkutil-modchecker-v1 1.0.11+4c66479160 via thonkutil
	- thonkutil-potions-v0 1.4.0+6d0d59d760 via thonkutil
	- thonkutil-titlescreen-v1 1.1.8+4c66479160 via thonkutil
	- thonkutil-trades-v1 1.1.19+4c66479160 via thonkutil
	- tlcosmetica 0.4.0 via visuality
	- toms_storage 1.3.0
	- totw_additions 1.2.1
	- tradingpost 3.2.0
	- trinketofundying 2.0.1-1.18
	- trinkets 3.3.0
	- tweed4_annotated 1.3.0 via wandering_collector
	- tweed4_base 1.5.0+mc1.18.2 via wandering_collector
	- tweed4_data 1.2.1+mc1.18.2 via wandering_collector
	- tweed4_data_hjson 1.1.0 via wandering_collector
	- tweed4_tailor_coat 1.1.2+mc1.18.2 via wandering_collector
	- tweed4_tailor_screen 1.1.1+mc1.18.2 via wandering_collector
	- twigs 1.1.3-patch1+1.18.2
	- universal_ores 1.2.1
	- universalbonemeal 3.0.4
	- vanilla_degus 1.3.0
	- veinmining 0.0.12-1.18.2
	- villager-hats 1.3.1
	- villagernames 4.0.3
	- visuality 0.4.2
	- visualworkbench 3.2.0
	- voidtotem 1.18.2-1.3.1
	- voidz 1.0.6
	- wandering_collector 1.1.2+mc1.18.2
	- waystones 2.5.0
	- windchimes 1.2.0
	- world-data 1.0.3-1.18.2 via postmateria
	- wthit 4.8.1
	- xaerominimap 22.5.0
	- xaeroworldmap 1.20.6
	- yigd 1.3.1
	- yungsapi 1.18.2-Fabric-2.0.7
	- zihlaunchpads 1.2.0
[11:25:45] [main/WARN]: Mod `bcc` (fabric-1.0.5) does not respect SemVer - comparison support is limited.
[11:25:45] [main/WARN]: Mod `endgoblintraders` (1.5 (Re-upload)) does not respect SemVer - comparison support is limited.
[11:25:45] [main/WARN]: Mod `fallingtree` (3.5.0b1) does not respect SemVer - comparison support is limited.
[11:25:45] [main/WARN]: Mod `mavm` (1.0.7a) does not respect SemVer - comparison support is limited.
[11:25:45] [main/WARN]: Mod `paintings` (9.1.1.0) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[11:25:45] [main/WARN]: Mod `terrablender` (1.1.0.99) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[11:25:48] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/DRBri/curseforge/minecraft/Install/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[11:25:48] [main/INFO]: Compatibility level set to JAVA_16
[11:25:48] [main/INFO]: Compatibility level set to JAVA_17
[11:25:48] [main/WARN]: Reference map 'axolotl-item-fix-refmap.json' for axolotlitemfix.mixins.json could not be read. If this is a development environment you can ignore this message
[11:25:48] [main/WARN]: Reference map 'biomemakeover-FABRIC-fabric-refmap.json' for biomemakeover.mixins.json could not be read. If this is a development environment you can ignore this message
[11:25:48] [main/INFO]: [MixinConfig] Not adding respawn_anchor_in_the_end.CheckIfCanSetSpawnMixin
[11:25:48] [main/INFO]: [MixinConfig] Not adding no_cured_villager_discount.BypassReputationGossipMixin
[11:25:48] [main/INFO]: [MixinConfig] Not adding no_treasure_enchantment_trading.CheckIfTradeableMixin
[11:25:48] [main/INFO]: Preparing DashLoader 3.1.1+1.18.
[11:25:48] [main/WARN]: Disabled Optional Feature FAST_STATE_INIT from dashloader config. DashLoader
[11:25:48] [main/WARN]: Disabled Optional Feature CACHE_PARTICLE from dashloader config. DashLoader
[11:25:48] [main/WARN]: Reference map 'ecologics-refmap.json' for ecologics.mixins.json could not be read. If this is a development environment you can ignore this message
[11:25:48] [main/ERROR]: 
[11:25:48] [main/ERROR]: 
[11:25:48] [main/ERROR]: 
[11:25:48] [main/ERROR]: 
[11:25:48] [main/ERROR]: bclib is incompatible with RecipeConfidence.
[11:25:48] [main/ERROR]: 
[11:25:48] [main/ERROR]: There is a chance that the compatibility layer is not correct, issues may arise
[11:25:48] [main/ERROR]: when using recipes (crafting, smelting, etc.) because of the conflict.
[11:25:48] [main/ERROR]: 
[11:25:48] [main/ERROR]: If you are the authors of bclib and have validated the compatibility layer, feel
[11:25:48] [main/ERROR]: free to make a mixin that changes BclibFlag.bclibCompatValidated to return true.
[11:25:48] [main/ERROR]: 
[11:25:48] [main/ERROR]: 
[11:25:48] [main/ERROR]: 
[11:25:48] [main/ERROR]: 
[11:25:48] [main/INFO]: Loaded configuration file for Lithium: 100 options available, 2 override(s) found
[11:25:48] [main/WARN]: Reference map 'pigsteel-fabric-1.18.2-refmap.json' for pigsteel.mixins.json could not be read. If this is a development environment you can ignore this message
[11:25:48] [main/WARN]: [Satin] Sodium is present, custom block renders may not work
[11:25:48] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 4 override(s) found
[11:25:49] [main/INFO]: [FANCYMENU] APPLYING MIXIN: de.keksuccino.fancymenu.mixin.client.MixinClickableWidget | TO TARGET: net.minecraft.class_339
[11:25:49] [main/INFO]: [FANCYMENU] APPLYING MIXIN: de.keksuccino.fancymenu.mixin.client.MixinEntryListWidget | TO TARGET: net.minecraft.class_350
[11:25:49] [main/INFO]: [FANCYMENU] APPLYING MIXIN: de.keksuccino.fancymenu.mixin.client.MixinMinecraftClient | TO TARGET: net.minecraft.class_310
[11:25:49] [main/INFO]: [FANCYMENU] APPLYING MIXIN: de.keksuccino.fancymenu.mixin.client.MixinTexturedButtonWidget | TO TARGET: net.minecraft.class_344
[11:25:49] [main/INFO]: [FANCYMENU] APPLYING MIXIN: de.keksuccino.fancymenu.mixin.client.MixinSplashScreen | TO TARGET: net.minecraft.class_425
[11:25:49] [main/INFO]: [FANCYMENU] APPLYING MIXIN: de.keksuccino.fancymenu.mixin.client.MixinDrawableHelper | TO TARGET: net.minecraft.class_332
[11:25:49] [main/INFO]: [FANCYMENU] APPLYING MIXIN: de.keksuccino.fancymenu.mixin.client.MixinAdvancementCommand | TO TARGET: net.minecraft.class_3008
[11:25:49] [main/INFO]: [FANCYMENU] APPLYING MIXIN: de.keksuccino.fancymenu.mixin.client.MixinOnlineServerEntry | TO TARGET: net.minecraft.class_4267$class_4270
[11:25:49] [main/INFO]: [FANCYMENU] APPLYING MIXIN: de.keksuccino.fancymenu.mixin.client.MixinWorldListEntry | TO TARGET: net.minecraft.class_528$class_4272
[11:25:49] [main/WARN]: Mixin malte0811.ferritecore.mixin.threaddetec.PalettedContainerMixin is disabled automatically as lithium is installed
[11:25:49] [main/WARN]: Error loading class: qouteall/imm_ptl/core/chunk_loading/ChunkDataSyncManager (java.lang.ClassNotFoundException: qouteall/imm_ptl/core/chunk_loading/ChunkDataSyncManager)
[11:25:49] [main/WARN]: @Mixin target qouteall.imm_ptl.core.chunk_loading.ChunkDataSyncManager was not found fiblib.mixins.json:CDSMAccessor
[11:25:49] [main/WARN]: Error loading class: qouteall/imm_ptl/core/chunk_loading/ChunkDataSyncManager (java.lang.ClassNotFoundException: qouteall/imm_ptl/core/chunk_loading/ChunkDataSyncManager)
[11:25:49] [main/WARN]: @Mixin target qouteall.imm_ptl.core.chunk_loading.ChunkDataSyncManager was not found fiblib.mixins.json:packets.chunkdata.MixinChunkDataSyncManager
[11:25:49] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[11:25:49] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton]) disables it and children
[11:25:49] [main/WARN]: Error loading class: net/dorianpb/cem/internal/config/CemConfig (java.lang.ClassNotFoundException: net/dorianpb/cem/internal/config/CemConfig)
[11:25:49] [main/WARN]: @Mixin target net.dorianpb.cem.internal.config.CemConfig was not found puzzle-gui.mixins.json:CemConfigAccessor
[11:25:49] [main/WARN]: Force-disabling mixin 'features.model.MixinMultipartBakedModel' as rule 'mixin.features.model' (added by mods [dashloader]) disables it and children
[11:25:49] [main/WARN]: Force-disabling mixin 'features.model.MixinWeightedBakedModel' as rule 'mixin.features.model' (added by mods [dashloader]) disables it and children
[11:25:49] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[11:25:49] [main/WARN]: Force-disabling mixin 'features.texture_updates.MixinSpriteInterpolated' as rule 'mixin.features.texture_updates' (added by mods [dashloader]) disables it and children
[11:25:49] [main/INFO]: I used the json to destroy the json
[11:25:49] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[11:25:50] [main/INFO]: Initializing DashLoader 3.1.1+1.18.
[11:25:50] [main/ERROR]: Found DashLoader 2.0 mod: adorn
[11:25:50] [main/INFO]: [130ms] Initialized api.
[11:25:50] [main/INFO]: Created DashLoader with KnotClassLoader.
[11:25:50] [main/INFO]: Initialized DashLoader
[11:25:51] [main/INFO]: Bootstrap start
[11:25:52] [main/WARN]: Method overwrite conflict for method_9522 in sodium.mixins.json:features.render_layer.leaves.MixinLeavesBlock, previously written by eu.midnightdust.cullleaves.mixin.MixinLeavesBlock. Skipping method.
[11:25:52] [main/WARN]: @Redirect conflict. Skipping moretags.mixins.json:item.shears.PumpkinBlockMixin->@Redirect::onUse$ItemStack$isOf(Lnet/minecraft/class_1799;Lnet/minecraft/class_1792;)Z from mod moretags with priority 1000, already redirected by bclib.mixins.common.json:shears.PumpkinBlockMixin->@Redirect::bn_useProxy(Lnet/minecraft/class_1799;Lnet/minecraft/class_1792;)Z from mod bclib with priority 1000
[11:25:52] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[client-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[client-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:19) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[fabric-loader-0.13.3-1.18.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2445 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[client-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[client-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:19) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[fabric-loader-0.13.3-1.18.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[client-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[client-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:19) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[fabric-loader-0.13.3-1.18.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector onUse$ItemStack$isOf(Lnet/minecraft/class_1799;Lnet/minecraft/class_1792;)Z in moretags.mixins.json:item.shears.PumpkinBlockMixin from mod moretags failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap MoreTags-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[client-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[client-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:19) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[fabric-loader-0.13.3-1.18.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
```

### Other mods

Using the Better Minecraft FABRIC Modpack but this also happens with just those Mods

### Additional Information

Moretags.mixins.json:item.shears.PumpkinBlockMixin is the Issue
Also tried adding this Mod but still same Issue: [More Tags]( https://www.curseforge.com/minecraft/mc-mods/more-tags

**Comment by StockiesLad** [comment]
Same here!

**Comment by ghost** [comment]
Uh same.. wanted to play with better end/nether but it causes crush with bclib

**Comment by Sunconure11** [comment]
Can confirm, it is because of the dependency MoreTags.

https://github.com/gudenau/minecraft-MoreTags/issues/14

**Comment by Sunconure11** [comment]
The mod is including an outdated build of More Tags. Update it, and the issue should be resolved.

**Comment by SHXRKIEgg** [comment]
> Can confirm, it is because of the dependency MoreTags.
> 
> [gudenau/minecraft-MoreTags#14](https://github.com/gudenau/minecraft-MoreTags/issues/14)
>
> The mod is including an outdated build of More Tags. Update it, and the issue should be resolved.

Nah already tried that as I mentioned still crashes. It doesn't even install the mod when you install Paradise Lost  and even with the Mod installed and it still crashes.

**Comment by Jack-Papel** [comment]
Thanks for reporting. This will not be fixed in tomorrow's update, however we are discussing it as a team

**Comment by HacoKavanah** [comment]
This crash was resolved in BCLib's 1.4.4 update, you seem to be using 1.4.3.

**Comment by Jack-Papel** [comment]
Needs confirmation whether this still occurs on 0.2.0

**Comment by PrismDraco** [comment]
> Needs confirmation whether this still occurs on 0.2.0

Can confirm. Trying to load Paradise Lost with BCLib still results in a crash. Currently using BCLib version 2.1.2, and Paradise Lost 2.0.

**Comment by TecEash1** [comment]
I have 

> > Needs confirmation whether this still occurs on 0.2.0
> 
> Can confirm. Trying to load Paradise Lost with BCLib still results in a crash. Currently using BCLib version 2.1.2, and Paradise Lost 2.0.

I have BCLIB v.2.1.0 installed (I need it for a separate dimension mod called Eden Ring) and it works perfectly with paradise lost - I don't know if this is something different or I have just done something strange

**Comment by PrismDraco** [comment]
> I have
> 
> > > Needs confirmation whether this still occurs on 0.2.0
> > 
> > 
> > Can confirm. Trying to load Paradise Lost with BCLib still results in a crash. Currently using BCLib version 2.1.2, and Paradise Lost 2.0.
> 
> I have BCLIB v.2.1.0 installed (I need it for a separate dimension mod called Eden Ring) and it works perfectly with paradise lost - I don't know if this is something different or I have just done something strange

I have Eden Ring as well. The only thing separating our cases is the BCLib version. 2.1.2 crashes, where 2.1.0 doesn't. Strange...

**Comment by PrismDraco** [comment]
One thing I'd like to add: BCLib released a new version about 3 hours ago at the time of writing this. I've tested the new 2.1.3 version and it also does not work with Paradise Lost.

**Comment by TecEash1** [comment]
> 

same here edit:(was referencing to the message before the last one)
[latest.log](https://github.com/devs-immortal/Paradise-Lost/files/10025193/latest.log)
- thats my log file

**Comment by PrismDraco** [comment]
I'm no good at analyzing stuff, but we both had this same error:
Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
Maybe this is tied to it. I don't know.

**Comment by Jack-Papel-RIT** [comment]
> I'm no good at analyzing stuff, but we both had this same error: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath Maybe this is tied to it. I don't know.

That pretty much always occurs. It's probably not related

**Comment by Jack-Papel-RIT** [comment]
Hmm, this is a @gudenau issue. Looks like MoreTags

**Comment by Jack-Papel-RIT** [comment]
> > 
> 
> same here [latest.log](https://github.com/devs-immortal/Paradise-Lost/files/10025193/latest.log)
> 
> * thats my log file

This issue appears to be related to capes, and not PL or BCLib

**Comment by PrismDraco** [comment]
Oh. Then what could the issue be?

**Comment by PrismDraco** [comment]
New version of BCLib dropped. I will test if it works with Paradise Lost.

**Comment by MBatt1** [comment]
Judging by the crash logs, it appears to be this mod/modloader? https://essential.gg/en/

I am not familiar with it but, there appears to be some incompatability with another mod, not with Paradise Lost

**Comment by TecEash1** [comment]
> Judging by the crash logs, it appears to be this mod/modloader? https://essential.gg/en/
> 
> 
> 
> I am not familiar with it but, there appears to be some incompatability with another mod, not with Paradise Lost

Wonder what mod that is - cuz I have essentials and it works perfectly 
Edit: sorry if I did not make myself clear, idk if u were referencing my log file or not, but mine seems to work with BClib atm

**Comment by PrismDraco** [comment]
It is not a problem with Essential. It crashes without it installed either way.

**Comment by PrismDraco** [comment]
I can send my crash logs and we can check if there are any recurring themes between TeEash1's crash and mine. Hopefully there is a common denominator.

**Comment by PrismDraco** [comment]
Also, to give extra context- From what I know, Essential is a mod that adds several QOL features, most around playing with friends, adding a friends list and the ability to play single player worlds with friends. I have used it a few times myself, and it typically works perfectly fine with mods.

**Comment by MBatt1** [comment]
Can you send a log without it? That might help reduce some of the console output I was suspecting the problem was.

**Comment by PrismDraco** [comment]
What version of Minecraft? 1.19.0?

**Comment by MBatt1** [comment]
1.19.2 should be the best with the latest

**Comment by ja2ui0** [comment]
I'm still having this issue (bclib is incompatible with RecipeConfidence) with Paradise Lost when any bclib mod (Better Nether, Better End, Eden Ring) is installed. All mods are Fabric 1.19.2 compat, and I only have a couple dozen loaded. LMK if you need log output, I will provide, but it's the same error with bclib.

**Comment by elpideus** [comment]
> I'm still having this issue (bclib is incompatible with RecipeConfidence) with Paradise Lost when any bclib mod (Better Nether, Better End, Eden Ring) is installed. All mods are Fabric 1.19.2 compat, and I only have a couple dozen loaded. LMK if you need log output, I will provide, but it's the same error with bclib.

Same here

**Comment by elpideus** [comment]
Solved. ModMenu was the problem for me.
